[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_port = COM8
monitor_port = COM8
lib_deps =
    SoftwareSerial
monitor_speed = 9600
build_unflags = -flto
build_flags = -Os -fno-lto -fno-toplevel-reorder